#!/bin/bash

START="$1"
ENDED="${2:-`date +%s`}"

if [[ -z "$START" || "$START" == "-h" || "$START" == "--help" ]]; then
  printf 'Usage: build-time START_UNIX [END_UNIX]\n'
  printf '       build-time FILE_PATH [END_UNIX]\n'
  exit 1
elif [[ -e "$START" ]]; then
  START=`stat -c %Y "$1"`
elif [[ ! "$START$ENDED" =~ ^[0-9]+$ ]]; then
  echo "Error: Start and/or end not valid."
  exit 1
elif [[ "$START" -ge "ENDED" ]]; then
  echo "Error: Start greater than or equal to end."
  exit 1
fi

DELTA=$(( ENDED - START ))                    # build in seconds

T=""                                          # output text
R=$DELTA                                      # remainder

D=$(( R / 86400 )); R=$(( R - (D * 86400) ))  # days
(( D > 0 )) && T="%d day(s), " || unset D

H=$(( R / 3600 )); R=$(( R - (H * 3600) ))    # hours
(( H > 0 )) && T+="%d hour(s), " || unset H

M=$(( R / 60 )); R=$(( R - (M * 60) ))        # minutes
(( M > 0 )) && T+="%d minute(s), " || unset M

S=$R                                          # seconds
if (( S > 0 )); then
  T+="%d second(s)"
else
  T="${T:0:-2}" # trim comma
  unset S
fi

printf "\nDate Started  : %s\nDate Completed: %s\n\nBuild Time    : $T\n" \
  "$START" "$ENDED" $D $H $M $S   # unquoted for a reason
